# Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    image: wazuh/wazuh:3.11.3_7.5.2
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"

  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.11.3_7.5.2
    hostname: elasticsearch
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=ES01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  kibana:
    image: wazuh/wazuh-kibana:3.11.3_7.5.2
    hostname: kibana
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
  nginx:
    image: wazuh/wazuh-nginx:3.11.3_7.5.2
    hostname: nginx
    restart: always
    volumes:
      - /data/docker/wazuh-docker/kibana.htpasswd:/etc/nginx/conf.d/kibana.htpasswd
    environment:
      - NGINX_PORT=443
      - NGINX_CREDENTIALS=user1:phunh123;
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kibana
    links:
      - kibana:kibana

volumes:
  esdata:
    driver: local
